export const ADS_LIST__REQUEST = 'ADS_LIST__REQUEST'
export const ADS_LIST__SUCCESS = 'ADS_LIST__SUCCESS'
export const ADS_LIST__FAIL = 'ADS_LIST__FAIL'

export const ADS_DETAILS__REQUEST = 'ADS_DETAILS__REQUEST'
export const ADS_DETAILS__SUCCESS = 'ADS_DETAILS__SUCCESS'
export const ADS_DETAILS__FAIL = 'ADS_DETAILS__FAIL'


export const SINGLE_ADD__REQUEST = 'SINGLE_ADD__REQUEST'
export const SINGLE_ADD__SUCCESS = 'SINGLE_ADD__SUCCESS'
export const SINGLE_ADD__FAIL = 'SINGLE_ADD__FAIL'