export const CARS_AVAIABLE_REQUEST = 'CARS_AVAIABLE_REQUEST'
export const CARS_AVAIABLE_SUCCESS = 'CARS_AVAIABLE_SUCCESS'
export const CARS_AVAIABLE_FAIL = 'CARS_AVAIABLE_FAIL'

export const CARS_RECOVER_REQUEST = 'CARS_RECOVER_REQUEST'
export const CARS_RECOVER_SUCCESS = 'CARS_RECOVER_SUCCESS'
export const CARS_RECOVER_FAIL = 'CARS_RECOVER_FAIL'

export const  CARS_DETAILS_REQUEST = ' CARS_DETAILS_REQUEST'
export const  CARS_DETAILS_SUCCESS = ' CARS_DETAILS_SUCCESS'
export const  CARS_DETAILS_FAIL = ' CARS_DETAILS_FAIL'