export const CONTRACTS_LIST_REQUEST = 'CONTRACTS_LIST_REQUEST'
export const CONTRACTS_LIST_SUCCESS = 'CONTRACTS_LIST_SUCCESS'
export const CONTRACTS_LIST_FAIL = 'CONTRACTS_LIST_FAIL'

export const CONTRACTS_CREATE_REQUEST = 'CONTRACTS_CREATE_REQUEST'
export const CONTRACTS_CREATE_SUCCESS = 'CONTRACTS_CREATE_SUCCESS'
export const CONTRACTS_CREATE_FAIL = 'CONTRACTS_CREATE_FAIL'

export const CONTRACTS_RETRIEVE_REQUEST = 'CONTRACTS_RETRIEVE_REQUEST'
export const CONTRACTS_RETRIEVE_SUCCESS = 'CONTRACTS_RETRIEVE_SUCCESS'
export const CONTRACTS_RETRIEVE_FAIL = 'CONTRACTS_RETRIEVE_FAIL'

export const CONTRACTS_UPDATE_REQUEST = 'CONTRACTS_UPDATE_REQUEST'
export const CONTRACTS_UPDATE_SUCCESS = 'CONTRACTS_UPDATE_SUCCESS'
export const CONTRACTS_UPDATE_FAIL = 'CONTRACTS_UPDATE_FAIL'

export const CONTRACTS_DELETE_REQUEST = 'CONTRACTS_DELETE_REQUEST'
export const CONTRACTS_DELETE_SUCCESS = 'CONTRACTS_DELETE_SUCCESS'
export const CONTRACTS_DELETE_FAIL = 'CONTRACTS_DELETE_FAIL'

export const CONTRACTS_APPROVE_REQUEST = 'CONTRACTS_APPROVE_REQUEST'
export const CONTRACTS_APPROVE_SUCCESS = 'CONTRACTS_APPROVE_SUCCESS'
export const CONTRACTS_APPROVE_FAIL = 'CONTRACTS_APPROVE_FAIL'

export const CONTRACTS_INTERMEDIATE_REQUEST = 'CONTRACTS_INTERMEDIATE_REQUEST'
export const CONTRACTS_INTERMEDIATE_SUCCESS = 'CONTRACTS_INTERMEDIATE_SUCCESS'
export const CONTRACTS_INTERMEDIATE_FAIL = 'CONTRACTS_INTERMEDIATE_FAIL'

export const CONTRACTS_DISAPPROVE_REQUEST = 'CONTRACTS_DISAPPROVE_REQUEST'
export const CONTRACTS_DISAPPROVE_SUCCESS = 'CONTRACTS_DISAPPROVE_SUCCESS'
export const CONTRACTS_DISAPPROVE_FAIL = 'CONTRACTS_DISAPPROVE_FAIL'