export const DRIVER_RECOVER_REQUEST = 'DRIVER_RECOVER_REQUEST'
export const DRIVER_RECOVER_SUCCESS = 'DRIVER_RECOVER_SUCCESS'
export const DRIVER_RECOVER_FAIL = 'DRIVER_RECOVER_FAIL'

export const DRIVER_UPDATE_REQUEST = 'DRIVER_UPDATE_REQUEST'
export const DRIVER_UPDATE_SUCCESS = 'DRIVER_UPDATE_SUCCESS'
export const DRIVER_UPDATE_FAIL = 'DRIVER_UPDATE_FAIL'

export const DRIVER_LIST_DRIVER_REQUEST = 'DRIVER_LIST_DRIVER_REQUEST'
export const DRIVER_LIST_DRIVER_SUCCESS = 'DRIVER_LIST_DRIVER_SUCCESS'
export const DRIVER_LIST_DRIVER_FAIL = 'DRIVER_LIST_DRIVER_FAIL'

export const DRIVER_CREATE_CONTRACTS_REQUEST = 'DRIVER_CREATE_CONTRACTS_REQUEST'
export const DRIVER_CREATE_CONTRACTS_SUCCESS = 'DRIVER_CREATE_CONTRACTS_SUCCESS'
export const DRIVER_CREATE_CONTRACTS_FAIL = 'DRIVER_CREATE_CONTRACTS_FAIL'

export const DRIVER_CREATE_RENTAL_REQUEST = 'DRIVER_CREATE_RENTAL_REQUEST'
export const DRIVER_CREATE_RENTAL_SUCCESS = 'DRIVER_CREATE_RENTAL_SUCCESS'
export const DRIVER_CREATE_RENTAL_FAIL = 'DRIVER_CREATE_RENTAL_FAIL'