export const OWNER_LIST_OF_CARS_REQUEST = 'OWNER_LIST_OF_CARS_REQUEST'
export const OWNER_LIST_OF_CARS_SUCCESS = 'OWNER_LIST_OF_CARS_SUCCESS'
export const OWNER_LIST_OF_CARS_FAIL = 'OWNER_LIST_OF_CARS_FAIL'

export const OWNER_RECOVER_OWNER_REQUEST = 'OWNER_RECOVER_OWNER_REQUEST'
export const OWNER_RECOVER_OWNER_SUCCESS = 'OWNER_RECOVER_OWNER_SUCCESS'
export const OWNER_RECOVER_OWNER_FAIL = 'OWNER_RECOVER_OWNER_FAIL'