export const REGISTER_CREATE_PERSON_REQUEST = 'REGISTER_CREATE_PERSON_REQUEST'
export const REGISTER_CREATE_PERSON_SUCCESS = 'REGISTER_CREATE_PERSON_SUCCESS'
export const REGISTER_CREATE_PERSON_FAIL = 'REGISTER_CREATE_PERSON_FAIL'

