export const RENT_LIST_REQUEST = 'RENT_LIST_REQUEST'
export const RENT_LIST_SUCCESS = 'RENT_LIST_SUCCESS'
export const RENT_LIST_FAIL = 'RENT_LIST_FAIL'

export const RENT_RETRIEVE_REQUEST = 'RENT_RETRIEVE_REQUEST'
export const RENT_RETRIEVE_SUCCESS = 'RENT_RETRIEVE_SUCCESS'
export const RENT_RETRIEVE_FAIL = 'RENT_RETRIEVE_FAIL'

export const RENT_CREATE_REQUEST = 'RENT_CREATE_REQUEST'
export const RENT_CREATE_SUCCESS = 'RENT_CREATE_SUCCESS'
export const RENT_CREATE_FAIL = 'RENT_CREATE_FAIL'

export const RENT_APPROVAL_REQUEST = 'RENT_APPROVAL_REQUEST'
export const RENT_APPROVAL_SUCCESS = 'RENT_APPROVAL_SUCCESS'
export const RENT_APPROVAL_FAIL = 'RENT_APPROVAL_FAIL'

export const RENT_DISAPPROVAL_REQUEST = 'RENT_DISAPPROVAL_REQUEST'
export const RENT_DISAPPROVAL_SUCCESS = 'RENT_DISAPPROVAL_SUCCESS'
export const RENT_DISAPPROVAL_FAIL = 'RENT_DISAPPROVAL_FAIL'

export const RENT_CANCEL_REQUEST = 'RENT_CANCEL_REQUEST'
export const RENT_CANCEL_SUCCESS = 'RENT_CANCEL_SUCCESS'
export const RENT_CANCEL_FAIL = 'RENT_CANCEL_FAIL'

export const RENT_END_REQUEST = 'RENT_END_REQUEST'
export const RENT_END_SUCCESS = 'RENT_END_SUCCESS'
export const RENT_END_FAIL = 'RENT_END_FAIL'